version: '3.8'

services:
  postgres:
    image: ${COMPOSE_PG_IMAGE:-postgres}:${COMPOSE_PG_VERSION:-16-alpine}
    environment:
      POSTGRES_USER: ${PG_USERNAME:?}
      POSTGRES_PASSWORD: ${PG_PASSWORD:?}
      POSTGRES_DB: ${PG_DATABASE:?}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: {}
